import Navbar from "./Navbar";
import Footer from "./Footer";
import styles from "./styles.module.css";
import { Outlet } from "react-router-dom";

export const metadata = {
  title: "HACCP",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <div className={`${styles.geistSans} ${styles.geistMono}`}>
      <Navbar />
      <div className={`${styles.layoutContainer}`}>
        <Outlet />
      </div>
      <Footer />
    </div>
  );
}
