
import Navbar from "./Navbar";
import Footer from "./Footer";
import styles from "./styles.module.css";

export const metadata = {
  title: "HACCP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <div className={`${styles.geistSans} ${styles.geistMono}`}>
        <Navbar />
        <div className={`${styles.layoutContainer}`}>{children}</div>
        <Footer />
      </div>

  );
}
